### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by gallegonovato** [D4rK7355608/com.d4rk.cleaner#85]
First of all, thank you for all your work and time. I would like to suggest a change, in the position of the buttons. Let me explain, on the main screen I think it would be better to put the button that says "Analyze" on the left or first hand. And then the "Clean" Since I understand that it would be better to analyze first. And then clean. and easier for users. and I take this opportunity to suggest a possibility of other languages. and I don't know if it is possible to upload it to fdroid. Jy without so many background permissions or internet access. A hug

**Comment by D4rK7355608** [comment]
Hello! I read your suggestion. Honestly I like to have buttons in default position. But... What u said makes me to think. That's why I work on o a setting to inverse button positions directly from the app is any user want it. So, stay tuned. :D
